export const apiPath = {
    login: "/login",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyOtp: "/verify-otp",
    logout: "/logout",
    getCountryCodes: "/get-countries",
    users: "/get-users",
    dashboard: "/get-dashboard",
    coupons: "/get-coupons",
    cities: "/get-update-cities",
    createCoupon: "/add-coupon",
    promoCodes: "/get-promo-code",
    couponInfo: "/get-coupon-info",
    deleteCoupons: "/delete-coupon",
    updateUserStatus: "/update-user-status",
    userInfo: "/get-user-info",
    getUpdatedCities: "/get-update-cities",
    getCountries: "/countries",
    getStates: "/states",
    getCitiesCustom: "/cities",
    addUpdateCustomCity: "/add-update-city",
    getContent: "/get-content",
    getUserSubscriptions: "/get-all-subscriptions",
    getPackages: "/get-packages",
    createPackage: "/add-package",
    getPackageInfo: "/get-package-info",
    updatePackageInfo: "/update-package",
    deletePackageInfo: "/delete-package",
    addPromoCode: "/add-promo-code",
    getPromoCodeInfo: "/get-promo-code-info",
    updatePromoCode: "/update-promo-code",
    deletePromoCode: "/delete-promo-code",
    getNotifications: "/get-notifications",
    deleteNotifications: "/delete-notifications",
    getFeedback: "/get-all-feedback",
    deleteFeedbacks: "/delete-feedback",
    getReplayFeedbackInfo: '/get-feedback-info',
    addReplayOnFeedback: '/add-feedback-replay'
};

//export const APP_URL = "http://13.235.91.193:3009/v1/admin";
export const APP_URL = "http://localhost:3009/v1/admin";
//export const APP_URL = "https://api.mycollegecards.com/v1/admin";