import { apiPath, APP_URL } from './apiPath';
import commonClient from "./appClient";
import commonClientUploadFile from "./appClientUploadFile";

export const login = (reqPayload) => commonClient.post(apiPath.login, reqPayload);
export const getUsers = (reqPayload) => commonClient.get(apiPath.users, { params: reqPayload });
export const getDashboard = () => commonClient.get(apiPath.dashboard, { params: {} });
export const getCoupons = (reqPayload) => commonClient.get(apiPath.coupons, { params: reqPayload });
export const getCities = (reqPayload) => commonClient.get(apiPath.cities, { params: reqPayload });
export const createCoupon = (reqPayload) => commonClientUploadFile.post(apiPath.createCoupon, reqPayload);
export const getPromoCode = (reqPayload) => commonClient.get(apiPath.promoCodes, { params: reqPayload });
export const getCouponInfo = (reqPayload) => commonClient.get(apiPath.couponInfo, { params: reqPayload });
export const deleteCoupons = (reqPayload) => commonClient.post(apiPath.deleteCoupons, reqPayload);
export const updateUserStatusinfo = (reqPayload) => commonClient.post(apiPath.updateUserStatus, reqPayload);
export const getUserInfo = (reqPayload) => commonClient.get(apiPath.userInfo, { params: reqPayload });
export const getUpdatedCities = (reqPayload) => commonClient.get(apiPath.getUpdatedCities, { params: reqPayload });
export const getCountries = (reqPayload) => commonClient.get(apiPath.getCountries, { params: reqPayload });
export const getStates = (reqPayload) => commonClient.get(apiPath.getStates, { params: reqPayload });
export const getCitiesCustom = (reqPayload) => commonClient.get(apiPath.getCitiesCustom, { params: reqPayload });
export const addUpdateCustomCity = (reqPayload) => commonClient.post(apiPath.addUpdateCustomCity, reqPayload);
