import { apiPath, APP_URL } from './apiPath';
import commonClient from "./appClient";
import commonClientUploadFile from "./appClientUploadFile";
import commonClientGuest from './appClientGuest'

export const login = (reqPayload) => commonClient.post(apiPath.login, reqPayload);
export const getUsers = (reqPayload) => commonClient.get(apiPath.users, { params: reqPayload });
export const getDashboard = () => commonClient.get(apiPath.dashboard, { params: {} });
export const getCoupons = (reqPayload) => commonClient.get(apiPath.coupons, { params: reqPayload });
export const getCities = (reqPayload) => commonClient.get(apiPath.cities, { params: reqPayload });
export const createCoupon = (reqPayload) => commonClientUploadFile.post(apiPath.createCoupon, reqPayload);
export const getPromoCode = (reqPayload) => commonClient.get(apiPath.promoCodes, { params: reqPayload });
export const getCouponInfo = (reqPayload) => commonClient.get(apiPath.couponInfo, { params: reqPayload });
export const deleteCoupons = (reqPayload) => commonClient.post(apiPath.deleteCoupons, reqPayload);
export const updateUserStatusinfo = (reqPayload) => commonClient.post(apiPath.updateUserStatus, reqPayload);
export const getUserInfo = (reqPayload) => commonClient.get(apiPath.userInfo, { params: reqPayload });
export const getUpdatedCities = (reqPayload) => commonClient.get(apiPath.getUpdatedCities, { params: reqPayload });
export const getCountries = (reqPayload) => commonClient.get(apiPath.getCountries, { params: reqPayload });
export const getStates = (reqPayload) => commonClient.get(apiPath.getStates, { params: reqPayload });
export const getCitiesCustom = (reqPayload) => commonClient.get(apiPath.getCitiesCustom, { params: reqPayload });
export const addUpdateCustomCity = (reqPayload) => commonClient.post(apiPath.addUpdateCustomCity, reqPayload);
export const getContent = (reqPayload) => commonClientGuest.get(apiPath.getContent, { params: reqPayload });
export const getUserSubscriptions = (reqPayload) => commonClient.get(apiPath.getUserSubscriptions, { params: reqPayload });
export const getPackages = (reqPayload) => commonClient.get(apiPath.getPackages, { params: reqPayload });
export const createPackage = (reqPayload) => commonClient.post(apiPath.createPackage, reqPayload);
export const getPackageInfo = (reqPayload) => commonClient.get(apiPath.getPackageInfo, { params: reqPayload });
export const updatePackageInfo = (reqPayload) => commonClient.post(apiPath.updatePackageInfo, reqPayload);
export const deletePackageInfo = (reqPayload) => commonClient.post(apiPath.deletePackageInfo, reqPayload);
export const addPromoCode = (reqPayload) => commonClient.post(apiPath.addPromoCode, reqPayload);
export const getPromoCodeInfo = (reqPayload) => commonClient.get(apiPath.getPromoCodeInfo, { params: reqPayload });
export const updatePromoCode = (reqPayload) => commonClient.post(apiPath.updatePromoCode, reqPayload);
export const deletePromoCode = (reqPayload) => commonClient.post(apiPath.deletePromoCode, reqPayload);
export const getNotifications = (reqPayload) => commonClient.get(apiPath.getNotifications, { params: reqPayload });
export const deleteNotifications = (reqPayload) => commonClient.post(apiPath.deleteNotifications, reqPayload);
export const getFeedback = (reqPayload) => commonClient.get(apiPath.getFeedback, { params: reqPayload });
export const deleteFeedbacks = (reqPayload) => commonClient.post(apiPath.deleteFeedbacks, reqPayload);
export const getReplayFeedbackInfo = (reqPayload) => commonClient.get(apiPath.getReplayFeedbackInfo, { params: reqPayload });
export const addReplayOnFeedback = (reqPayload) => commonClient.post(apiPath.addReplayOnFeedback, reqPayload);
export const createContent = (reqPayload) => commonClient.post(apiPath.createContent, reqPayload);
export const getVersion = (reqPayload) => commonClient.get(apiPath.getVersion, { params: reqPayload });
export const updateVersionAll = (reqPayload) => commonClient.post(apiPath.updateVersionAll, reqPayload);
export const deletedUsersInfo = (reqPayload) => commonClient.post(apiPath.deleteUser, reqPayload);